### PR TITLE
Added Feature Request Button and Form

### LINKED ISSUE #52: Add link to submit feature request into site footer
**Is your feature request related to a problem? Please describe.**
I want to be able to submit a feature request to the site.

**Describe the solution you'd like**
I want to see a link on the front page and be able to make a feature request by clicking it.

**Describe alternatives you've considered**
Add a link.

**Additional context**
This could be added in the footer of the page.

### PR DESCRIPTION
**Pull request by adhammo**
Resolves #52 .

**Why this pull request exists?**

Added feature request button and form which relies on [Getform.io](https://getform.io/) to handle feature requests storage.

**Changes made in this pull request:**
- Added a feature request page "feature.jsx" to gatsby website pages (src/pages/) and it has a FeaturePage component as its content.
- Created a feature request form inside FeaturePage component.
- Added a feature request button to website footer which is a link to the feature request gatsby page.
- The feature request button is not visible in the feature request page and in order to do that I obtained the path given by gatsby in both index.jsx and feature.jsx and gave it to the Footer component through the Layout component.

**Showcase:**
*Feature Request Page*
Feature Request Page

**Feature Request Button*
Feature Request Button

*Feature Request in Action*
Feature Request in Action
Getform in Action

**Note:**
Don't forget to change the action link for the feature request form to you [Getform.io](https://getform.io/) form.
Getform handler

@turkupy/turkypy-maintainers

### CODE REVIEW

**Comment by magdapoppins** [comment]
Hi @adhammo! Thanks for this very thorough pr! 
I'm sorry if we have been unclear when writing this issue, but we would like the link to lead to the GitHub submit issue page, that is 
`https://github.com/turkupy/turkupy.github.io/issues/new?assignees=&labels=&template=feature_request.md&title=`
So we get those issues directly to this repository. 
Could you update your pr accordingly?

**Comment by adhammo** [comment]
OK! I'll do so.

**Comment by adhammo** [comment]
OK! I did it. I ended up deleting some of the things I made earlier though. Tell me if you wanted me to refork the repo and open a new pull request to just add the feature request button.

**Comment by adhammo** [comment]
Hey,
Are there problems with the PR? if not, can you please label this PR as hacktoberfest-accepted?

**Review by eevajonnapanula — CHANGES_REQUESTED** [review]
Thank you for your work! There were some things (see comments) about styling and accessibility related stuff, so requesting changes based on them.

**Comment by adhammo** [comment]
I fixed the issues you specified.
- Removed extra styling.
- Made the link open in the same page.
- Added "Request feature" to **translation.json**.

I want to say it would be better if you used Redux to handle langCode if you wanted to change it through the header or smth.

**Comment by eevajonnapanula** [comment]
I see your point about using state management instead of passing the lang code down. However, I don't see Redux as and answer in our case as it is pretty heavy solution for our (small) site, and there are other tools that are lighter. We could either use React's Context-API, or just read the lang code from the url. But thanks for your feedback, we take it into consideration!

**Pull request merged**
