### PR TITLE
Feature/upcoming events

### LINKED ISSUE #23: Add "Upcoming events"
Would be good to have an "Upcoming events" section, similar to "Past events"

### PR DESCRIPTION
**Pull request by eevajonnapanula**
Resolves #23.

**Why this pull request exists?**
We needed to have the upcoming events on the front page too. 

**Changes made in this pull request:**
- Adds a separate Events-page, where all the (future and past) events are shown
- Separates upcoming and past events on the front page, also shows only 4 of the past events.

So the front page would change into this (showing just the Events-part):
Turkupy site with separated Upcoming events and Past events sections

So what changes, is that there is that "Upcoming events"-section (which is currently empty) and from "Past events" would only last 4 to be shown. Also, there's a link to the events-page.

On the Events-page, there would be all of the events:

Screenshot 2020-10-20 at 15 56 30

Again, upcoming events are empty, and all the past events would be listed here.

### CODE REVIEW

**Review by magdapoppins — COMMENTED** [review]
I'd love to see a screenie as part of this pr! Sorry for taking so long to notice, I see there has been quite a rebase operation going on... If you have the energy, it would be awesome if you could clean up the history and just do one final merge at the end of the pr?

Also, did you add those newlines in md files or were they from a merge or did your editor auto-add them? We could maybe add some autoformatter as part of actions?

Thanks for your patience and help and sorry for being a slow reviewer! 🙇🏼‍♀️

**Comment by eevajonnapanula** [comment]
Good point, I will add one later today/tomorrow the latest! 😊 

And what do you mean with one final merge? Like, do you mean something before pushing the "merge" button? ('cos I've been using this "Squash and merge"-option for merging PRs, so it would just squash the commits into one)

Which newlines? 🤔  When looking into the Files changed-tab, I can't see any changes to the md-files 😅  But you are right, adding autoformatter would be beneficial as, for example, the pre-commit-hooks are run only when editing on IDE, and not when doing edits in Github. I'll add an issue about that later.

**Comment by magdapoppins** [comment]
> Good point, I will add one later today/tomorrow the latest! 😊
> 
> And what do you mean with one final merge? Like, do you mean something before pushing the "merge" button? ('cos I've been using this "Squash and merge"-option for merging PRs, so it would just squash the commits into one)
> 
> Which newlines? 🤔 When looking into the Files changed-tab, I can't see any changes to the md-files 😅 But you are right, adding autoformatter would be beneficial as, for example, the pre-commit-hooks are run only when editing on IDE, and not when doing edits in Github. I'll add an issue about that later.

👀 I seem to be losing it, I was sure that there were some markdown files with added newlines in those files but now I also don't see them! Probably somewhere in those merges. Squash and merge sounds like a good option, as long as the commit msg contains all the info from your commits (or some kinda summary)! 👍🏼

**Comment by magdapoppins** [comment]
> @magdapoppins added some screenies to the description 😊
> 
> And yeah, that will contain a list of commits in the "description" of the commit (so the longer one), and as a "title" of the commit is always the name of the Pull request

Ok, screenies look gr8! 🚀  I'd prefer that the commit history would be re-written so that it wouldn't contain any repetition or unnecessary noise, but descriptive commit messages of the actual steps. But that's just nitpicking, this looks quite ok! Maybe for future reference. I think having a clear and clean git history is a great help in looking back in time.

Will approve when the conflicts are resolved! 💪🏼

**Comment by eevajonnapanula** [comment]
This is interesting. I mean, I don't see any conflicts 😅  

And an example of how squash and merge does this is here: https://github.com/turkupy/turkupy.github.io/commit/b3f01e659257530865f0126402f2da71d578eb79

So the there's one commit per merged PR, but there's the list of commits in the description of the merge commit. I think it's also a neat way to combine all things done, and it looks more clean in the repository's code view, as the commits are "Name of the PR (#number of PR)". But yeah, maybe inside of them (as in that list of commits, so before merge)  some cleaning up could be done too.

**Review by magdapoppins — APPROVED** [review]

**Pull request merged**
